using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class AmbientSound
{
    [HideInInspector] public string name;
    public Sound sound;
    public Vector2 waitTimeRange = new Vector2(4, 8);
    public float distanceFromCamera = 2;
    [HideInInspector] public float cooldown;
    [HideInInspector] public Transform transform;

    public void Play()
    {
        transform.localPosition = Random.insideUnitSphere * distanceFromCamera;
        sound.Play(transform);
        cooldown = Random.Range(waitTimeRange.x, waitTimeRange.y);
    }
}

public class MusicPlayer : MonoBehaviour
{
    [SerializeField] List<Sound> mainMusics = new List<Sound>();
    [SerializeField] Sound altMusic, pauseMusic, ambientLoop;
    [SerializeField] Vector2 silenceWaitRange = new Vector2(1, 10);
    [SerializeField] bool fadeIn = true;
    public bool playAltMusic;
    bool playingMainMusic, fadingOut;
    float mainMusicTimeLeft;

    public int CurrentSong;

    private Sound mainMusic => mainMusics[CurrentSong];

    [Header("Ambience")]
    [SerializeField] List<AmbientSound> ambientSounds = new List<AmbientSound>();

    private void OnValidate()
    {
        foreach (var a in ambientSounds) if (a.sound != null) a.name = a.sound.name;
    }

    private void Start()
    {
        foreach (var a in ambientSounds) {
            a.sound = Instantiate(a.sound);
            a.transform = new GameObject(a.name + " source (AmbientSound)").transform;
            a.transform.parent = Camera.main.transform;
            a.cooldown = Random.Range(a.waitTimeRange.x, a.waitTimeRange.y);
        }

        for (int i = 0; i < mainMusics.Count; i++) mainMusics[i] = Instantiate(mainMusics[i]);
        if (ambientLoop) ambientLoop = Instantiate(ambientLoop);
        if (pauseMusic) pauseMusic = Instantiate(pauseMusic);
        if (altMusic) altMusic = Instantiate(altMusic);

        if (pauseMusic) pauseMusic.PlaySilent();
        if (altMusic) altMusic.PlaySilent();
        if (ambientLoop) {
            if (fadeIn) ambientLoop.PlaySilent();
            else ambientLoop.Play();
        }

        StartNext(fadeIn);
    }

    public void FadeOutCurrent(float time)
    {
        mainMusicTimeLeft = Mathf.Infinity;
        StartCoroutine(FadeOut(time));
    }

    IEnumerator FadeOut(float time)
    {
        float mainStart = mainMusic.percentVolume;
        float ambientStart = ambientLoop ? ambientLoop.percentVolume : 0;
        float altStart = altMusic ? altMusic.percentVolume : 0;
        float pauseStart = pauseMusic ? pauseMusic.percentVolume : 0;

        fadingOut = true;
        float timePassed = 0;
        while (timePassed < time) {
            float progress = timePassed / time;

            mainMusic.SetPercentVolume(Mathf.Lerp(mainStart, 0, progress));
            if (ambientLoop) ambientLoop.SetPercentVolume(Mathf.Lerp(ambientStart, 0, progress));
            if (altMusic) altMusic.SetPercentVolume(Mathf.Lerp(altStart, 0, progress));
            if (pauseMusic) pauseMusic.SetPercentVolume(Mathf.Lerp(pauseStart, 0, progress));

            timePassed += Time.deltaTime;
            yield return new WaitForEndOfFrame();
        }
    }

    void StartNext(bool silent = false)
    {
        if (silent) foreach (var m in mainMusics) m.PlaySilent();
        else foreach (var m in mainMusics) m.Play();
        mainMusicTimeLeft = mainMusic.GetClipLength();
        playingMainMusic = true;
    }

    private void Update()
    {
        if (fadingOut) return;

        foreach (var a in ambientSounds) {
            a.cooldown -= Time.deltaTime;
            if (a.cooldown <= 0) a.Play();
        }

        float pausedMod = Time.timeScale == 0 ? 0 : 1;
        if (playAltMusic && altMusic) PlayAltMusic(pausedMod);
        else PlayNormalMusic(pausedMod);

        if (ambientLoop) ambientLoop.SetPercentVolume(pausedMod, 0.01f);
        if (pauseMusic) pauseMusic.SetPercentVolume(1 - pausedMod, 0.01f);
    }

    void PlayAltMusic(float pausedMod)
    {
        mainMusic.SetPercentVolume(0, 0.1f);
        altMusic.SetPercentVolume(1 * pausedMod, 0.1f);
    }

    void PlayNormalMusic(float pausedMod)
    {
        if (playingMainMusic) mainMusic.SetPercentVolume(1 * pausedMod, 3 * Time.deltaTime);
        foreach (var m in mainMusics) if (m != mainMusic) m.SetPercentVolume(0, 1 * Time.deltaTime);
        if (altMusic) altMusic.SetPercentVolume(0, 0.1f);

        mainMusicTimeLeft -= Time.deltaTime;
        if (mainMusicTimeLeft > 0) return;

        if (!playingMainMusic) {
            StartNext();
            return;
        }
        playingMainMusic = false;
        mainMusicTimeLeft = Random.Range(silenceWaitRange.x, silenceWaitRange.y);
    }
}
